services:
  nuxt_dev:
    container_name: nuxt3_typescript_eslint_starter_dev
    build: .
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0 # ! Обязательно, иначе не пробрасываются порты
    ports:
      - "${EXTERNAL_NUXT_PORT}:3000"
      - "24678:24678" # hmr
    volumes:
      - "./app:/app/"
      - "./logs:/root/.npm/_logs"
    restart: always
    command: bash -c "npm run dev"
    # command: bash -c "node debug-container.js"